<?=$this->doctype()?>

<html>

<head>
	<?=$this->headTitle($this->siteParam("core-admin-title"))->setSeparator($this->siteParam("core-site-title-sep"))?>
	<?php $this->appendCss("/atp-admin/css/admin.less")?>
	<?=$this->headLink()?>
	
	<?php $this->prependJs("/atp-admin/js/admin.js")
		->prependJs("/atp-core/js/tiny_mce/jquery.tinymce.js")
		->prependJs("/atp-core/js/tiny_mce/tiny_mce.js")
		->prependJs("/atp-core/js/jquery-ui-1.10.3.custom.min.js")
		->prependJs("/atp-core/js/jquery-1.10.2.min.js")
	?>
	<?=$this->headScript()?>
</head>

<body>
	<div id="page">
		<div id="page-content">
			<?=$this->partial('atp-admin/shared/admin_menu.phtml', array('menu' => $this->menu))?>
			
			<?=$flash?>

			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</body>

</html>
