<?=$this->doctype()?>

<html>

<head>
	<?=$this->headTitle($this->siteParam("Admin Title"))->setSeparator(" | ")?>
	<?=$this->headLink()
		->appendStylesheet($this->basePath() . "/atp-admin/css/admin.css")
		->appendStylesheet($this->basePath() . "/atp-core/css/redmond/jquery-ui-1.10.3.custom.min.css")
	?>
	<?=$this->headScript()
		->prependFile($this->basePath() . "/atp-admin/js/admin.js")
		->prependFile($this->basePath() . "/atp-core/js/tiny_mce/jquery.tinymce.js")
		->prependFile($this->basePath() . "/atp-core/js/tiny_mce/tiny_mce.js")
		->prependFile($this->basePath() . "/atp-core/js/jquery-ui-1.10.3.custom.min.js")
		->prependFile($this->basePath() . "/atp-core/js/jquery-1.10.2.min.js")
	?>
</head>

<body>
	<div id="page">
		<div id="page-content">
			<?=$flash?>
			
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</body>

</html>
