<?=$this->doctype()?>

<html>

<head>
	<?=$this->headTitle($this->siteParam("core-admin-title"))->setSeparator($this->siteParam("core-site-title-sep"))?>
	<?php $this->appendCss("/atp-admin/css/admin.less")?>
	<?=$this->headLink()?>
	
	<?=$this->headScript()
		->prependFile($this->basePath() . "/atp-admin/js/admin.js")
		->prependFile($this->basePath() . "/atp-core/js/tiny_mce/jquery.tinymce.js")
		->prependFile($this->basePath() . "/atp-core/js/tiny_mce/tiny_mce.js")
		->prependFile($this->basePath() . "/atp-core/js/jquery-ui-1.10.3.custom.min.js")
		->prependFile($this->basePath() . "/atp-core/js/jquery-1.10.2.min.js")
	?>
</head>

<body>
	<div id="page">
		<div id="page-content">
			<?=$flash?>
			
			<?php echo $this->layout()->content; ?>
		</div>
	</div>
</body>

</html>
