<form method="post" enctype="multipart/form-data">
	<h2>
		Admin &gt; <a href="<?=$this->url('admin', array('action' => 'list', 'model' => $model))?>"><?=\ATP\Inflector::pluralize($modelData['displayName'])?></a> &gt;
		<?php if($object->id) { ?>
			Editing <?=$modelData['displayName']?> - <?=$object->displayName()?>
		<?php } else { ?>
			Creating New <?=$modelData['displayName']?>
		<?php } ?>
		<input type="submit" class="model-save" name="save-and-edit" value="Save and Continue Editing" />
		<input type="submit" class="model-save" name="save" value="Save" />
	</h2>

	<div id="admin-tabs">
		<ul>
			<?php foreach(array_keys($modelData['tabs']) as $tab) { ?>
				<li><a href="#object-<?=\ATP\Inflector::underscore($tab)?>-tab"><?=$tab?></a></li>
			<?php } ?>
			<?php foreach(array_keys($modelData['customTabs']) as $tab) { ?>
				<li><a href="#object-<?=\ATP\Inflector::underscore($tab)?>-tab"><?=$tab?></a></li>	
			<?php } ?>
		</ul>
	
		<input type="hidden" name="modelData[id]" value="<?=$object->id?>" />
		<?php foreach($modelData['tabs'] as $tab => $columns) { ?>
			<div id="object-<?=\ATP\Inflector::underscore($tab)?>-tab">
				<div class="admin-edit model-edit-form">
					<?php foreach($columns as $column) { ?>
						<?php if($object->isOwnerField($column)) { ?>
							<?php $table = $object->ownerTable($column) ;?>
							<?php $ownerField = \ATP\Inflector::variablize(str_replace("_id", "", $column)); ?>
							<?=$this->formModelSelect(array(
								'label' => \ATP\Inflector::titleize($ownerField),
								'name' => "modelData[{$column}]",
								'className' => get_class($object->$ownerField),
								'value' =>$object->$ownerField->id
							))?>
							<?php if($object->$ownerField->id) { ?>
								<!--<a href="<?=$this->url('admin' ,array('action' => 'edit', 'model' => $column, 'id' =>$object->$ownerField->id))?>">Edit <?=$column?></a>-->
							<?php } ?>
						<?php } else { ?>
							<?php $columnData = $modelData['fields'][$column]?>
							<?php $helper = "form{$columnData['type']}"?>
							<?=$this->$helper(array('label' => $columnData['label'], 'name' => "modelData[{$column}]", 'value' => $object->$column))?>
							<?php if($object->isAFile($column) && !empty($object->$column->name)) { ?>
								<a class="file-link" href="<?=$this->basePath($object->filePath($column))?>" target="blank">View File</a>
							<?php } ?>
						<?php } ?>
						
					<?php } ?>
				</div>
			</div>
		<?php } ?>
		<?php foreach($modelData['customTabs'] as $tab => $template) { ?>
			<div id="object-<?=\ATP\Inflector::underscore($tab)?>-tab">
				<?=$this->partial($template, array('object' => $object))?>
			</div>
		<?php } ?>
	</div>
</form>

<p class="admin-return">
	<a href="
</p>
