<h2>
	<?php if($object->id) { ?>
		Edit <?=\ATP\Inflector::titleize($model)?> - <?=$object->displayName()?>
	<?php } else { ?>
		Create New <?=\ATP\Inflector::titleize($model)?>
	<?php } ?>
</h2>

<div id="admin-tabs">
	<ul>
		<li><a href="#object-details-tab">Details</a></li>
		<?php if($object->id) { ?>
			<?php foreach($object->subObjectFields() as $singular => $plural) { ?>
				<li><a href="#<?=$plural?>-tab"><?=$plural?></a></li>
			<?php } ?>
			<?php foreach($object->relatedObjectFields() as $singular => $data) { ?>
				<?php $plural = \ATP\Inflector::pluralize($singular)?>
				<li><a href="#<?=$plural?>-tab"><?=$plural?></a></li>
			<?php } ?>
		<?php } ?>
	</ul>
	
	<div id="object-details-tab">
		<div class="admin-edit model-edit-form">
			<form method="post" enctype="multipart/form-data">
				<input type="hidden" name="id" value="<?=$object->id?>" />
				
				<div class="owner-field-list">
					<?php foreach($object->ownerFields() as $column => $table) { $columnUnderscore = \ATP\Inflector::underscore($column); ?>
						<?=$this->formModelSelect(array('label' => $column, 'name' => "{$columnUnderscore}_id", 'className' => get_class($object->$column), 'value' =>$object->$column->id))?>
						<?php if($object->$column->id) { ?>
							<!--<a href="<?=$this->basePath() . "/admin/edit/{$columnUnderscore}/{$object->$column->id}"?>">Edit <?=$column?></a>-->
						<?php } ?>
					<?php } ?>
				</div>
				
				<?php foreach($object->dataColumns() as $column) { ?>
					<?php $columnData = $modelData['fields'][$column]?>
					<?php $helper = "form{$columnData['type']}"?>
					<?=$this->$helper(array('label' => $columnData['label'], 'name' => \ATP\Inflector::underscore($column), 'value' => $object->$column))?>
					<?php if($object->isAFile($column) && !empty($object->$column->name)) { ?>
						<a class="file-link" href="<?=$this->basePath() . $object->filePath($column)?>" target="blank">View File</a>
					<?php } ?>
				<?php } ?>
				
				<input type="submit" class="model-save" name="submit" value="Save <?=\ATP\Inflector::titleize($model)?>" />
			</form>
		</div>
	</div>
	
	<?php if($object->id) { ?>
		<?php foreach($object->subObjectFields() as $singular => $plural) { ?>
			<div id="<?=$plural?>-tab">
				<div class="admin-edit">
					<?php $field = lcfirst($singular) . 'List'?>
					<?php /*<?=$this->partial('admin/model_list.phtml', array('objects' => $object->{$field}, 'delete' => false))?> */ ?>
					<?php /*Add <?=$singular?> <?=$this->partial('form/model_select.phtml', array('column' => "new_{$singular}", 'obj' => $object->{$field}->temp()))?> */?>
				</div>
			</div>
		<?php } ?>
		<?php foreach($this->object->relatedObjectFields() as $singular => $data) { ?>
			<?php $plural = \ATP\Inflector::pluralize($singular)?>
			<div id="<?=$plural?>-tab">
				<div class="admin-edit">
					<?php $field = lcfirst($singular) . 'List'?>
					<?php /* <?=$this->partial('admin/model_list.phtml', array('objects' => $object->{$field}, 'delete' => false))?> */ ?>
					<?php /*Add <?=$singular?> <?=$this->partial('form/model_select.phtml', array('column' => "blah", 'obj' => $object->{$field}->temp()))?>*/ ?>
				</div>
			</div>
		<?php } ?>
	<?php } ?>
</div>

<p class="admin-return">
	<a href="<?=$this->basePath() . "/admin/list/{$model}"?>">Back to <?=\ATP\Inflector::pluralize(\ATP\Inflector::titleize($this->model))?></a>
</p>