<h2><?=$modelData['category']?> &gt; <?=\ATP\Inflector::pluralize($modelData['displayName'])?></h2>

<?=$paginator?>

<?=$this->partial('atp-admin/shared/model_list.phtml', array('objects' => $objects, 'model' => $model, 'modelData' => $modelData, 'delete' => true))?>

<?=$paginator?>

<div id="dialog-confirm" title="Deleting the <?=$model?>">
	<p>
		<span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 6em 0;"></span>
		<b id="deleted-model-name">Item Name</b><br/><br/>
		This <?=$modelData['displayName']?> will be permanently deleted and cannot be recovered.<br/><br/>
		<em>Are you sure you want to delete this <?=$modelData['displayName']?>?</em>
	</p>
</div>
