<h2><?=$label?></h2>

<table class="report admin-model-list">
	<thead>
		<tr>
			<?php foreach($columns as $column) { ?>
				<th class="ui-widget-header ui-corner-all"><?=$column?></th>
			<?php } ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($data as $row) { ?>
			<tr>
				<?php foreach($columns as $column) { ?>
					<td><?=$row->$column?></td>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
</table>
