<div id="admin-header">
	<h1><a href="<?=$this->basePath() . "/admin"?>"><?=$this->siteParam('Admin Title')?></a></h1>
	<a id="logout-link" href="<?=$this->basePath() . "/admin/logout"?>">Logout</a>
	<span id="id-span">Hi {{adminUser:}}!</span>
	<ul id="admin-menu">
		<?php foreach($menu as $category => $menuItems) { ?>
			<li>
				<a href=""><?=$category?></a>
				<ul>
					<?php foreach($menuItems as $item) { ?>
						<li>
							<a href="<?=$this->basePath() . $item['link'] ?>">
								<?=$item['label']?>
							</a>
						</li>
					<?php } ?>
				</ul>
			</li>
		<?php } ?>
	</ul>
</div>