<div id="admin-header">
	<h1><a href="<?=$this->basePath() . "/admin"?>">##Admin Title##</a></h1>
	<a id="logout-link" href="<?=$this->basePath() . "/admin/logout"?>">Logout</a>
	<span id="id-span">Hi ##Current User##!</span>
	<ul id="admin-menu">
		<?php foreach($menu as $category => $models) { ?>
			<li>
				<a href=""><?=$category?></a>
				<ul>
					<?php foreach($models as $modelData) { ?>
						<li>
							<a href="<?=$this->basePath() . "/admin/list/" . \ATP\Inflector::underscore($modelData['model']) ?>">
								<?=\ATP\Inflector::pluralize($modelData['name'])?>
							</a>
						</li>
					<?php } ?>
				</ul>
			</li>
		<?php } ?>
	</ul>
</div>