<div id="admin-header">
	<div id="main-header">
		<h1><a href="<?=$this->url('admin')?>"><?=$this->siteParam('Admin Title')?></a></h1>
		<a id="logout-link" href="<?=$this->url('admin', array('action' => 'logout'))?>">Logout</a>
		<span id="id-span">Hi {{adminUser:}}!</span>
	</div>
	<ul id="admin-menu">
		<?php foreach($menu as $category => $menuItems) { ?>
			<li>
				<a href=""><?=$category?></a>
				<ul>
					<?php foreach($menuItems as $item) { ?>
						<li>
							<a href="<?=$this->url('admin', $item['linkData'])?>">
								<?=$item['label']?>
							</a>
						</li>
					<?php } ?>
				</ul>
			</li>
		<?php } ?>
	</ul>
</div>