<p>
	<a class="model-new" href="<?=$this->url('admin', array('action' => 'edit', 'model' => $model))?>">
		Create a new <?=$modelData['displayName']?>
	</a>
</p>

<table class="admin-model-list">
	<thead>
		<tr>
			<td class="ui-widget-header ui-corner-all"><?=$modelData['displayName']?></td>
			<?php foreach($modelData['displayColumns'] as $column) { ?>
				<td class="ui-widget-header ui-corner-all"><?=$column?></td>
			<?php } ?>
			<td class="ui-widget-header ui-corner-all" colspan=2>Actions</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach($objects as $obj) { ?>
			<tr>
				<td><?=$obj->displayName()?></td>
				<?php foreach($modelData['displayColumns'] as $column) { ?>
					<td><?=$obj->$column?></td>
				<?php } ?>
				
				<td class="button-cell">
					<a class="edit-link admin-list-button" href="<?=$this->url('admin', array('action' => 'edit', 'model' => $model, 'id' => $obj->identity()))?>">Edit</a>
				</td>
				<?php if($this->delete) { ?>
					<td class="button-cell">
						<a class="delete-link admin-list-button" href="<?=$this->url('admin', array('action' => 'delete', 'model' => $model, 'id' => $obj->identity()))?>">Delete</a>
					</td>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
</table>
