<p>
	<a class="model-new" href="<?=$this->basePath() . "/admin/edit/{$model}"?>">
		Create a new <?=\ATP\Inflector::singularize(\ATP\Inflector::titleize($this->objects->modelType()))?>
	</a>
</p>

<table class="admin-model-list">
	<thead>
		<tr>
			<?php foreach($modelData['displayColumns'] as $column) { ?>
				<td class="ui-widget-header ui-corner-all"><?=$column?></td>
			<?php } ?>
			<td class="ui-widget-header ui-corner-all" colspan=2>Actions</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach($objects as $obj) { ?>
			<tr>
				<?php foreach($modelData['displayColumns'] as $column) { ?>
					<td><?=$obj->$column?></td>
				<?php } ?>
				
				<td class="button-cell">
					<a class="edit-link admin-list-button" href="<?=$this->basePath() . "/admin/edit/{$model}/{$obj->identity()}"?>">Edit</a>
				</td>
				<?php if($this->delete) { ?>
					<td class="button-cell">
						<a class="delete-link admin-list-button" href="<?=$this->basePath() . "/admin/delete/{$model}/{$obj->identity()}"?>">Delete</a>
					</td>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
</table>
